env:
  global:
    - secure: nj8UFNRGai8pmMzdO4Bt2+o7xJJ0KwehUzgBgExc9uTE7LfRVBAeWG9Lgh4IkvKb/BmXqS7aM7VSIHtacCTYdelris+WuWlEb9xpSMoPAQn0zdO6JOx/BM8LSt8dlgkxn0Bl2zQSus7m491i1l2b5d/bw1i7Qp5SqcveF8GsCsv31LrmJ2/eCNTX/d/OA3zG+Z10wpVuYFUAGiuN3hH5+hUWDtCjkIsmCXKDg2gHYiwDNNcE8LdvnUmhU1fGc275eRhOJuKFHqGKJp7LDWGwXUwVA9t4kyZNPHU+i6TzH+qsAmCYHbU2hM+R/r6a0S2+nhvBcRUi8v4CBdmInPT/FJ5m1JO64O2A8s9x/+7nqvApzqDjSxm4KA0Ey2wWn1N1J7a7klb6noNxnrCgDeR7fgIQE9PQNGz9ntuv1BimRQluT5zc+V2Zte/IBq+4Y/53yGuG/zrtQ3LWBQm1T9Izh2mLRqdXmIlFHGTJo+Fndl0Ll82fG6mHAX9mpJk/Vv7g/eWW3w0pjAm03RDAcKczEupBBQsraRb0Fccx9bOXQENYV5H9RNIXDbin1VbiUk2OjmdN743wt0c67TQVQRp6H5UbNYXrkjpbse62yj97CB1ZANCI2HPspbX4Q03hDbLrG1B9hZAzkKBz1ltRYuX9Qi4AnodX2Yel2LL4Bjz9+Uw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
