env:
  global:
    - secure: QCtTqzJE+Vlb1ZbxUycxnNj5QhkHDiazLrp5Vs+OCcLM+kYWcSf2DOJ64IY63m2eEClRzNNJ1xzrVgmZwAUBp5Y/1NMqsLDqDiekf7DVmF1hAM3j09B3iK+zu7C0n/0rz0ftxPt/MmBIWTiXGpzc1Kq264n6ejJLFT52RAzX6PT9HSfiv+PFalX02ZARrH1Jr6dPOBoioOTwjs96j4kcG88QLG1/LuuRauVcr2slp4TXmljOHYCC2cCb16YFMUS8NZ9yqHicy87zDuMJM2bqxhS3yVvd5zogDG1nuplY97C9QEst5RnieXFcuYe6b8nulPsK465FChFVs5fGlif64WrmKmmZoWTPtF02wnU8jCKjWqmJpngGE7RLy4+kmMsGUjOB5dOPLZHNvL4Q8SE9ZC9iwCdtDdfN5Csu3OT7NNwuvxNLnZ8gr6rV9r0QTvQua1QSoA9XN02bC3p/8ZujAdThd6va5iseP6fGChMwOjE724HPy7qEz8GdYOehRIIsmMOukl116TWbCEsya3Var0Ct8erkI6yS2SOYoWEIpOYQpG+PTSCBuRwkNXkzNmOB85BXC8iJTKJVp1YIF87DW1n/+ZLgtfFiosTm1LOz3Fefuug0Qh53EYA2N4clt50GGOoNiLylWZhBI4aWE0rBpoItT0Cq0+eBTVbTIinj3y4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
