env:
  global:
    - secure: D5nZ0O0YD+6q9s0iJy18347D65rv/AVVpFho18KzpjDLefI8oYqWXICnE7tMmX0g8sVcNEhe8YiH9dEd1Yjf5nlhbiarMY2BoRn+Lm++iCeU6MwgWrr4Q9tKerCiLOpmJgFH6wanrQyPoG8ZHV8EnP9OhnKYs5wtkKvObN1il+VAMw/xuER23YQXiokyMcDGE1fnh+KzlgcHOtsF+qrmkvkGMUCQMj9+hI2knW1Fg3ZY2USxLLHWZqRL/kLqnTs4CoB9xHKffLDiIVyhSYDstCrq8GiuFdno1kAb36ZU6OdIchZGPmNJDrJeBk+h3mmdEYtUJ6ZUSi83mZzVPX1UyBCDKJzDdBUUxYeHXw2d9qOaqCHhLbZzcNnjaNEAUFU4jWbcWNNOyPavp+YF0qKYW13qNuI+r8VwQLd1Y9DUMMscvg5arC0b7Cx38SZiLAKZkdUMAEC3B9lzSW9Ra/bifP+nlcgzs9R1sISe2cg0HthiB5ZxoWHNqd6uyelqJVXnrAedkx8veBOKEOh86DmD88ptBtj5z2TTaU0N32jUhzY2onqH0nIwfinsCMQFMDmocY00OKs+NMIVY5yrDHCCziOFYf/wH6xj5/c/AShEvVzjjcIeKbAzQ0ELdvV0U0jdNfE1BnHdrSIC8v3gM+z+W7SgDcXt04Qfq4wYNiMpIiM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
