env:
  global:
    - secure: NxRxU0E7/wAbX3XEARyZAtxyrre4PF8KDh2SyFMYQpYlTuwjIiAJruFuMEAYk+qM/+a21IRaUScKC/WXTv5YWS1orcmvjuQOKEuIsNFcS1wa4YZPIhlMseWEgpsthzDMyBi067TD3akF8dtxhbRyO1VESo9RYaRW26TXe7nOLrWEmcgg4qQzOHjk/IieqllM2aDAmb6M9y5VsxGxc6u8trIu5WrdcL5M0GGkS1PIB0Famq6nE4DvnqE3U9njou+TXCBj71JmADaYRNrJsnFE7op0ZgF4EnMLdQR0lWJ8IT0Jh7K2w5OeXVGODbtN3xOJXscoAI66be9zdh4LnHKtSUfyBtFtzJbj2dR4l7xXqofi54CiKVcpPOnbQPiMKbroEsZh+g4mAE5/YvhrTQrHz9OQZr9WFia7hv3NvmTsl+GJjEcd3xBLDhXd5LNqt4CEUVTOOK3Ds+eZFrlBYsRmBnbduPbrb1UrIRXY/rbFE3BT9dHY+NmJIhG4HH37BGN1LvE+4v5r2yNHLRW0J79TmDDpBmgz5a5B42wu8F9X3cQ6qGc5zqVTXC+aoWDTpuXpTfGojapkLoSW6q9AfMbBMcpwB6dVFEZeAPun63O0j+1uaNc2km6McbbN8R/y6Z5b0k3sxAjSGBnd6D/XR7JuBJy75qGPJSjG1b8LvJPpdm4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
