env:
  global:
    - secure: XI0RYgW2Fr/T6iBrtUlgFofBE3zZ+B4LPwD5lBXL7CD7U5pJ6Z9O3/Mnfax93FdXk4R2Fdw8eX2LLMVR05pQAqlVjzKPECNJd+jM69Jsbfl3nZlTAI/5K6X+gCLMR6Bi3EXyetuUCdsugisdap5xsKG4OnZW/nCMAZvX36qbXawRtUCfqetrx0C4Pe3TrW6OtyYS73pFbW3N2GKbh4Ou/guvBH011c0IeQbKK9UHH5YKSha1YY452QaTywAz5ZQJhGYpNUiRtBpPUpzL/zl2vB+PcZwbotsrVCWysnXYI9+RKECflHgDYgkRoMGRq/o5jfbEsWF9/IvcbkedjNVS8k+/0VMy+ouTkQexXyK2MxlYhxo8e3Ppegzaj1/IcDquRMQdj5AdJ4tKJbgKEM4AiJk8hFzjnWrkewEfsIMcwZgAv4y+UKdDcsp5Vqiz1OVg+qSMAX+F4JNfv5M/IF1WPq6x7JbhcdqJ/IKLvI+ts2IIo5EnPquCWQyGbIWRAwOKZF0p1FvYmHaPBN62Ji1z01P53aGnmg0lgdSw0mUqYIVXGlFjskG3s0GNz6JZh27VNbD5fCQg+/hoe5OEs/EIlNbjP3TbLy8t11SnLO81DvuHxgdIvrdDUXXz+/f1aY78vnUJ3Um99LbxqxFl2pr1XKnJecwyVhQwOjAzFNffNSA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
