env:
  global:
    - secure: mOXq10/fNLUYkpX4+BCuVR5FxgpV8ezpLgkU+c/tbd1K19ldQ3S+p8D3nqVx7lC4JLIMRSyYyhLIYT3adiariKfybw35lkmZaoSa38n5iBQQ0iutujXF2BFUrj47q0bLDkmUjzYGRvIA2rvxu/sA+Ebl82e2pwXfGIw07AJpI0/m9zii/a0w9QI20OzFSl9gi7eCoVyF/5GmlGSCsryOF6tF6gQcicG3EQQfZIC+r9QkRLC1xedQy+8sBfAKVkx4bNg+llk3FVtiISPRJTWHstrWpGiJO9Pb78CoFcOKbRQCmaAN2NwKIkKI1gai+aKUzJx0TmdKtfEFKfSlEh+P3EJweoxJ2e243ov+M6TDFyQqzbwE6PZJKJC8J9DX/hdZxC5xQLQMBBOjHLp0DaoYti+pg/D7I/lDIlgEMghqcJOQtaenLsZGRb4/5FDySSXN1giRACc/47JeBYC9JPXjA9TmfuT5n+DhI1aJvXwDd8/ETrCzAMYcdm0Q2DBIPQp65b7sYdpqX6Hv5HuZNHgagNjZTtdn2p8yIrF5IMoCZatl1ufEuzikZdlJXCFaGDXOmrVpLOaAfKmxEv2SF3rL3F/nxofV/9EFW+w/fgAnb7b5shQnBwvTXIf3r8gMqjaOjCQIMBCWG8ZgsmiRpqbH1rxFTdEoMaeYigJw8/PjVLg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
