env:
  global:
    - secure: MDaAfNSlxlXRCuHjuwRZRVPExqfXoFtbu79s/RTJLsNuGBxfqINkMlAN9Z2uVO5DAi/coEY99NNIDER4MEZbSQkoJCCo0OOMdudSA64BeXuIqH1SfokDctE9m7bqrSg5U4pHTjWCN+ruwcrn39wX9LJStK3bWvwUquiUEaaTgfllTmZ+7TrfaWUF3E9PJTNEYOcQGFKc0DINKlK6p7kdG7LZ+NGUAFpq9jMlnrmVxOWkSKBUgzvKVccMmvO1YQxreUVDz372sMKYUEPJCcdSytpHeIIFX8NoaOkahTFh09qX5VdKwWPr38xO/ibZiEgT5XTUbSJqQ3Yv88PFJsZ1zSoypiLqAJrPyc7BfQxXvh+3PN4U4uHlmtlyTHgAmDrn6ccug8MdTHda3MHke6MLIm3Cj9d/Oct1wSLnqi5L/G/FyEP1eJzy3eqFbMW5u3TpB3hGXGs2AxK5w2EkTXt76/PI8dXMAGpL+uV3dJgCSYxAA3mrAkD+hMNUpn5Pi2LfNHvv/EM4sdyZe0D4duHSdxhFXri2RdQIYANa7Voze7vY/UbGeSikLKEbCr2cGD7DWsokRfFlZkHwDzXrqYgbjS/qIK//S1V04NCZ+1vu63BuLD1Kxwa4ujSHxoxhcUh4bai70mIExexoYgff+XpuhfmQracoJ6dc0VNux9FQH9g=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
