env:
  global:
    - secure: O/iPgM9ElBqL8rjO5tvjw687HEFh+7SL7UJaZe7aSlEbPMEtjOOaWE1PzdGdRA1xqEOeBnsqc/7JgDw2LhEsfLB34D7OhO9wxG9tanYTz84DHVSSXwYJoNIRY0JqgmffRrlqV7oEhiKLxN/+trsK/rQLDIsaoZfpJ2V73FK64HreIY+himDt6P0F9TF3X0i5Ff7fYGC7REtHr7SmzHjlIsdGwMTZkPwSOOB2Txj/I/GVz919c2DP5eoTztUUC2maw29baE46YWXGviXvA0g0+0xxUY9YMaK4INjg4xQJGBkCrMiqhv3QhQ0R+a3DnT+HeJKF1AgXpX2Rye6/43TdXemADvBM8XUEW0BDf/0L1EbSqz7c7COmmleGCG417aetk5yldX7/VfDrNbdhNS0KGnBzNYcJzOMPWFr/Y0roxhE/4GG9EQb5tFQAcFIAU3u9cOpj4nJgNDEJyIFjPRemlWXOZZ6FTcPc846HPYnN2uJuUVSyi5DD38U/haqywM40yl9zfe8grg/3Jsf0YJOgSFuSyNsIo6XlFTdbHS6tyMjY95RQBfzVUbGVTHphAt1wwd+irkwurr4DIgEc1O8ZTeBoNCGDiTr56A4jz0qLT7toKjVg0Gta/7d/0kOW9/cRXh0eN18Kdn2HrH790ZcHJOgQpwep1d0qp3EYo8AchIo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
