env:
  global:
    - secure: HXpyAZUhizPTQ/l4yisO/NACKxBilv/6UGxFlFD27MOOACQ6n328vjwoDxzb7I6CQIDNmT7y6n4hsHlL7lYmUXFBhfnQffr3fHU/KImeIwN//BN6YJiP63sHXMuXoChQESIiZeXomMy5j2Alb3tIARzLVLdnMvIdgZ/iKS4qqbP5tu89mJS60o/WQcrGKxlkMvik8FbQ++PUKYUT/NrDbY+CegehmNXXdklE+X2E2Qxj++MK9w2IbDbUZ2ibYIVMBsqvEjFTx+gW4x/rNYwT/4fYScOUYtMy1rsL5TOEzCm8C4Xt91C+fckQt0Fa3TBUfoFtKtaoWd3o8sA4If1J4NZoPFLJBBz3MLX7f4SCh6jLtHh2KPclMjlHnnvwn+D/MIlnr2Jdk6Z1y4BvEMZT0ai2MpD3S1UE9gGVZ2BLNrWBmjzYgkhm2KVKx2hpzUeKNb22VTZt+1WL4e+5gtH7ayTomPYJ+1brivtlvG91u9S/gvhaAi9Dnuhqr++Iqdiv2QCz7xwn/aAhusfXUMy/mevdy6aMsuDGiCuhNTEySQjHH8qK75rL/NEO2dgfp8jOvrWrutG6nfRh7lPhZ9O67hDrN+gBiT0Lo/q9+/e3vKkO3H7ffSxpvK5pcEVGcSMjtuwuwPh3xGrmKGW+rvCOzjEpcztOuf7ZZ30GAD6PTCA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
