env:
  global:
    - secure: HCWtX5CoWaCBOlHNCPOAyTbnl/swSvdFvbepQyJ/NNiDph2Ongbqbz5XBnPqneyLnVdUCppvC395Vod24pb3N0xTeqN7FjDJ78EIByzNeKoCOleCsfjF0InVPlreEJfcMXDjXTCoXtUjGXh/MTisGuqxE97/6G7V+ihbMWbxD7HocoQAihNNOSatJ6x5DSQWXfr9qurOAAitrNddCWzeuC0kIKjjCAusQuXfikGKs4HoHVL30glxyIi5Tfmq67sgNDPHOzrnu0MiktBRWN8Pcshl0JBw9hd4AEUbgM+IzcdZ8QqzmpwV6/KuQigPuxqfrfSluqXISgdXd9piLXMvpidK9rffYCPcueNs5I6HCokbTrbNNsFipvIVv3u3lYsHowPP+xBbCzAgbS5uLBMK/B1ZsYpJqVTeTFHOEOHMLpyPyDEd7B1/ussI7gtHr+JCf3CPjZDihu3eRBnkBe3r65mIyQW+eJO4I9ScE8FJD2nxOQ6q28bVWsTCJxnzIbtiIg7A0wIy9MXuuqeh0/mUyOI2ZKj+KtITPkHrAYdrruUjv0zTUP2IUWTzSQBFfQBe4r260uw0KYnL+2OTJGVTqkS7mxzoU1BqGkXkCtNdXy0dJq1uTMfSA/iXPACs27tPwCjb9Hn7cwLY6u3e+5+Wbr7T3zYjHf4ipbeIytU1SIE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_web_yoyo.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
